name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Optional: Run tests if you have any
    # - name: Run tests
    #   run: |
    #     pytest tests/

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed gui.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: FishTracker-exe
        path: dist/gui.exe
