name: Build and Release FishTracker EXE

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # ✅ This line allows GitHub Actions to upload release assets

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: pyinstaller gui.py --noconfirm --onefile --name FishTracker

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/FishTracker.exe
